; All units herein are GeV, units of e-, ns, unless otherwise noted

; Settings for milli charged particle

[ParticleProperties]

; job configuration settings, to make sure we have no fourvector overlaps
JobNumber = 0
EventsPerJob = 1000
EventWeight = 1.0
ProcessID = 1

; These are relevant only if particle is monopole, ignored if anything else
MagneticCharge = 0.0
ElectricCharge = 1
; ElectricCharge = 0.01
; MonopoleMass = 0.1
MonopoleMass = 0.106

; 3x2 bars are 17 cm tall, 11 cm wide, which is reflected here
yParticleGunRescale = 6
zParticleGunRescale = 0.1

Particle = mu-
; Particle = monopole
; set to mu- for muon

FileName = muon_hit_4_vecs_large.txt
PathName = /home/ryan/test/milliQanSim/inputData/

coincidenceThreshold = 2
